## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('dsdvq', ['internet'])
    module.includes = '.'
    module.source = [
        'model/dsdvq-rtable.cc',
        'model/dsdvq-packet-queue.cc',
        'model/dsdvq-packet.cc',
        'model/dsdvq-routing-protocol.cc',
        'helper/dsdvq-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('dsdvq')
    module_test.source = [
        'test/dsdvq-testcase.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'dsdvq'
    headers.source = [
        'model/dsdvq-rtable.h',
        'model/dsdvq-packet-queue.h',
        'model/dsdvq-packet.h',
        'model/dsdvq-routing-protocol.h',
        'helper/dsdvq-helper.h',
        ]
    if (bld.env['ENABLE_EXAMPLES']):
      bld.recurse('examples')

    bld.ns3_python_bindings()
